[tool.black]
target-version = ["py311"]
force-exclude = '''
/(
  \.git
  |\.venv
  |venv
  |\.mypy_cache
  |\.pytest_cache
  |__pycache__
  |__init__\.py
)/
'''
line_length = 88


[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "LOCALFOLDER"]
length_sort = true
line_length = 88
group_by_package = true
skip_glob = "*/venv/*,*/.venv/*,*/__init__.py"

[flake8]
max-line-length = 88
exclude = [".git", "__pycache__", "__init__.py", ".mypy_cache", ".pytest_cache", "venv", ".venv"]
extend-ignore = ["E203", "E501"]